id = "infracost-ls"
name = "Infracost"
version = "0.1.0"
schema_version = 1
authors = ["Infracost <hello@infracost.io>"]
description = "Cloud cost estimates and FinOps policies for Terraform and CloudFormation"
repository = "https://github.com/infracost/zed-infracost"

[language_servers.infracost-ls]
name = "Infracost"
languages = ["Terraform", "JSON", "YAML"]
